/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DemoKeyRouteImport } from './routes/demo/$key'
import { Route as AppCleanupIndexRouteImport } from './routes/_app/cleanup/index'
import { Route as AppPeopleIndexRouteImport } from './routes/_app/people/index'
import { Route as AppPeoplePersonIdRouteImport } from './routes/_app/people/$personId'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppServicesServiceTypeIdPlansPlanIdRouteRouteImport } from './routes/_app/services/$serviceTypeId/plans/$planId/route'
import { Route as AppServicesServiceTypeIdPlansPlanIdIndexRouteImport } from './routes/_app/services/$serviceTypeId/plans/$planId/index'
import { Route as AppServicesServiceTypeIdPlansPlanIdViewRouteImport } from './routes/_app/services/$serviceTypeId/plans/$planId/$view'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoKeyRoute = DemoKeyRouteImport.update({
  id: '/demo/$key',
  path: '/demo/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCleanupIndexRoute = AppCleanupIndexRouteImport.update({
  id: '/cleanup/',
  path: '/cleanup/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleIndexRoute = AppPeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => AppRoute,
} as any)
const AppPeoplePersonIdRoute = AppPeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesServiceTypeIdPlansPlanIdRouteRoute =
  AppServicesServiceTypeIdPlansPlanIdRouteRouteImport.update({
    id: '/services/$serviceTypeId/plans/$planId',
    path: '/services/$serviceTypeId/plans/$planId',
    getParentRoute: () => AppRoute,
  } as any)
const AppServicesServiceTypeIdPlansPlanIdIndexRoute =
  AppServicesServiceTypeIdPlansPlanIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppServicesServiceTypeIdPlansPlanIdRouteRoute,
  } as any)
const AppServicesServiceTypeIdPlansPlanIdViewRoute =
  AppServicesServiceTypeIdPlansPlanIdViewRouteImport.update({
    id: '/$view',
    path: '/$view',
    getParentRoute: () => AppServicesServiceTypeIdPlansPlanIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/$key': typeof DemoKeyRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/cleanup/': typeof AppCleanupIndexRoute
  '/people/': typeof AppPeopleIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/services/$serviceTypeId/plans/$planId': typeof AppServicesServiceTypeIdPlansPlanIdRouteRouteWithChildren
  '/services/$serviceTypeId/plans/$planId/$view': typeof AppServicesServiceTypeIdPlansPlanIdViewRoute
  '/services/$serviceTypeId/plans/$planId/': typeof AppServicesServiceTypeIdPlansPlanIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/$key': typeof DemoKeyRoute
  '/people/$personId': typeof AppPeoplePersonIdRoute
  '/cleanup': typeof AppCleanupIndexRoute
  '/people': typeof AppPeopleIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/services/$serviceTypeId/plans/$planId/$view': typeof AppServicesServiceTypeIdPlansPlanIdViewRoute
  '/services/$serviceTypeId/plans/$planId': typeof AppServicesServiceTypeIdPlansPlanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/admin/$': typeof AdminSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/demo/$key': typeof DemoKeyRoute
  '/_app/people/$personId': typeof AppPeoplePersonIdRoute
  '/_app/cleanup/': typeof AppCleanupIndexRoute
  '/_app/people/': typeof AppPeopleIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/services/$serviceTypeId/plans/$planId': typeof AppServicesServiceTypeIdPlansPlanIdRouteRouteWithChildren
  '/_app/services/$serviceTypeId/plans/$planId/$view': typeof AppServicesServiceTypeIdPlansPlanIdViewRoute
  '/_app/services/$serviceTypeId/plans/$planId/': typeof AppServicesServiceTypeIdPlansPlanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/admin/$'
    | '/api/$'
    | '/demo/$key'
    | '/people/$personId'
    | '/cleanup/'
    | '/people/'
    | '/services/'
    | '/services/$serviceTypeId/plans/$planId'
    | '/services/$serviceTypeId/plans/$planId/$view'
    | '/services/$serviceTypeId/plans/$planId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/admin/$'
    | '/api/$'
    | '/demo/$key'
    | '/people/$personId'
    | '/cleanup'
    | '/people'
    | '/services'
    | '/services/$serviceTypeId/plans/$planId/$view'
    | '/services/$serviceTypeId/plans/$planId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/auth'
    | '/admin/$'
    | '/api/$'
    | '/demo/$key'
    | '/_app/people/$personId'
    | '/_app/cleanup/'
    | '/_app/people/'
    | '/_app/services/'
    | '/_app/services/$serviceTypeId/plans/$planId'
    | '/_app/services/$serviceTypeId/plans/$planId/$view'
    | '/_app/services/$serviceTypeId/plans/$planId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  AdminSplatRoute: typeof AdminSplatRoute
  ApiSplatRoute: typeof ApiSplatRoute
  DemoKeyRoute: typeof DemoKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$key': {
      id: '/demo/$key'
      path: '/demo/$key'
      fullPath: '/demo/$key'
      preLoaderRoute: typeof DemoKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/cleanup/': {
      id: '/_app/cleanup/'
      path: '/cleanup'
      fullPath: '/cleanup/'
      preLoaderRoute: typeof AppCleanupIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/': {
      id: '/_app/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof AppPeopleIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/people/$personId': {
      id: '/_app/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof AppPeoplePersonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$serviceTypeId/plans/$planId': {
      id: '/_app/services/$serviceTypeId/plans/$planId'
      path: '/services/$serviceTypeId/plans/$planId'
      fullPath: '/services/$serviceTypeId/plans/$planId'
      preLoaderRoute: typeof AppServicesServiceTypeIdPlansPlanIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$serviceTypeId/plans/$planId/': {
      id: '/_app/services/$serviceTypeId/plans/$planId/'
      path: '/'
      fullPath: '/services/$serviceTypeId/plans/$planId/'
      preLoaderRoute: typeof AppServicesServiceTypeIdPlansPlanIdIndexRouteImport
      parentRoute: typeof AppServicesServiceTypeIdPlansPlanIdRouteRoute
    }
    '/_app/services/$serviceTypeId/plans/$planId/$view': {
      id: '/_app/services/$serviceTypeId/plans/$planId/$view'
      path: '/$view'
      fullPath: '/services/$serviceTypeId/plans/$planId/$view'
      preLoaderRoute: typeof AppServicesServiceTypeIdPlansPlanIdViewRouteImport
      parentRoute: typeof AppServicesServiceTypeIdPlansPlanIdRouteRoute
    }
  }
}

interface AppServicesServiceTypeIdPlansPlanIdRouteRouteChildren {
  AppServicesServiceTypeIdPlansPlanIdViewRoute: typeof AppServicesServiceTypeIdPlansPlanIdViewRoute
  AppServicesServiceTypeIdPlansPlanIdIndexRoute: typeof AppServicesServiceTypeIdPlansPlanIdIndexRoute
}

const AppServicesServiceTypeIdPlansPlanIdRouteRouteChildren: AppServicesServiceTypeIdPlansPlanIdRouteRouteChildren =
  {
    AppServicesServiceTypeIdPlansPlanIdViewRoute:
      AppServicesServiceTypeIdPlansPlanIdViewRoute,
    AppServicesServiceTypeIdPlansPlanIdIndexRoute:
      AppServicesServiceTypeIdPlansPlanIdIndexRoute,
  }

const AppServicesServiceTypeIdPlansPlanIdRouteRouteWithChildren =
  AppServicesServiceTypeIdPlansPlanIdRouteRoute._addFileChildren(
    AppServicesServiceTypeIdPlansPlanIdRouteRouteChildren,
  )

interface AppRouteChildren {
  AppPeoplePersonIdRoute: typeof AppPeoplePersonIdRoute
  AppCleanupIndexRoute: typeof AppCleanupIndexRoute
  AppPeopleIndexRoute: typeof AppPeopleIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppServicesServiceTypeIdPlansPlanIdRouteRoute: typeof AppServicesServiceTypeIdPlansPlanIdRouteRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppPeoplePersonIdRoute: AppPeoplePersonIdRoute,
  AppCleanupIndexRoute: AppCleanupIndexRoute,
  AppPeopleIndexRoute: AppPeopleIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppServicesServiceTypeIdPlansPlanIdRouteRoute:
    AppServicesServiceTypeIdPlansPlanIdRouteRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  AdminSplatRoute: AdminSplatRoute,
  ApiSplatRoute: ApiSplatRoute,
  DemoKeyRoute: DemoKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
